# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_has_quiz_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qna',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
