# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mentors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
