# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_mentors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mentors',
        ),
        migrations.AddField(
            model_name='mentors',
            name='girl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='girl', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='mentors',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='users.UserProfile'),
        ),
    ]
