# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170303_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='qna',
            new_name='common_answers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
