# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170302_1652'),
        ('users', '0010_auto_20170303_1926'),
    ]

    operations = [
    ]
