# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170307_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/static/images/icons/avatar.png', upload_to='userpics/'),
        ),
    ]
