# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170323_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
